### ISSUE TITLE
[Feature request] Dedicated options to specify state.db and the configuration folder

### ISSUE THREAD

**Issue by StayPirate** [skx/rss2email#138]
### Context

I was looking for a way to easily manage rss2email's configuration files (`feeds.txt` and templates) via git. For that I created a [_companion_ container](https://github.com/StayPirate/git-local-sync) which shares a common volume with the `rss2email`'s container and its only task is to keep the volume content in sync with a remote git repository.

This companion container is just [a simple bash script](https://github.com/StayPirate/git-local-sync/blob/master/git-local-sync) polling a remote git repository and pull data in case it has changed.

In my case, the remote repository [contains rss2email's configuration data](https://github.com/StayPirate/sieve-disroot/tree/master/rss2email). Data is synced in a volume that is also mounted by the rss2email container, this way rss2email sees any change sent to the remote repository. And this will allow the user (me) **to conveniently manage templates and feeds via git**.

### Real case example

I created [this docker compose stack](https://github.com/StayPirate/stack-rss2email/blob/master/docker-compose.yml) where the two containers are configured to share a common volume named `rss2email_config`:

```yaml
services:

  rss2email_git-local-sync:
    [...]
    volumes:
      - "rss2email_config:/repo"

[...]

  rss2email:
    [...]
    volumes:
      - "rss2email_state:/app/.rss2email/state"
      - "rss2email_config:/app/.rss2email/config:ro"
```

### Limitation

Unfortunately, rss2email expects to find (or attempt to write) the `state.db` file in the same location. This is sub-optimal for my setup, because I'd like to mount the common volume in read-only mode on the rss2email's container.

### Feature request

In order to make my setup work I need some extra configuration flexibility from rss2email. Would be possible to add two new cmdline options, one to specify a custom path for the configuration folder (`feeds.txt` and templates) and the other to specify a custom pathname for `stated.db`?

I think something like the following might work: 
```bash
rss2email \
    --config /app/.rss2email/config/rss2email \
    --state /app/.rss2email/state/state.db \
    daemon user@email.com
```
